### ISSUE TITLE
Edit does not modify data

### ISSUE THREAD

**Issue by Schroedingberg** [4ka0/django_htmx_books#1]
Great example!
But the edit buttons are not working properly yet.

**Comment by Schroedingberg** [comment]
I've found the cause of the error, but I don't have time for a PR right now. The `hx-post` and `hx-target` tags of the save button in  `partial_device_update_form.html ` need to be in the form tags, not the button tags.

**Comment by 4ka0** [comment]
Thanks for the comments. Much appreciated.
I just tested this out but the edit and save functionality seems to be working okay in my version. 
Out of curiosity, I moved the `hx-post` and `hx-target` tags into the form tags but then the edit functionality no longer worked in my version.
I'm not sure what's causing the difference but your comment above should help anyone else if they have the same issue.
Thanks again.
